"""Initial migrations

Revision ID: ce5e8cc6632d
Revises: 
Create Date: 2024-05-12 23:49:26.779256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ce5e8cc6632d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'healthcheck' not in inspector.get_table_names():
        op.create_table(
            "healthcheck",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            ),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )

    if 'pdf_records' not in inspector.get_table_names():
        op.create_table(
            "pdf_records",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("pdf_name", sa.String, nullable=False),
            sa.Column("location", sa.String, nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("healthcheck")
    op.drop_table("pdf_records")
    # ### end Alembic commands ###
